.\" Process this file with
.\" groff -man -Tascii xiv.1
.\"
.TH XIV 1 "JULY 2010" Linux "User Manuals"
.SH NAME
xiv \- Simple Image Viewer
.SH SYNOPSIS
.B xiv [options] file1 file2...
.SH DESCRIPTION
.B xiv
is a very simple image viewer without UI and only controled by keys and mouse.
As opposed to most of the image viewers, it does not rely on scrollbar for image panning.
It is a powerful tool to analyse huge images.
The Window is a view of the image in which you can zoom, pan, rotate...
xiv reads natively 8 and 16 bits binary PPM and TIFF and JPEG images. It uses ImageMagick to convert other formats.
Image drawing is performed in several threads for a better image analysis experience.
Next image is preloaded during current image analysis.
See usage for the full list of features.

.B xiv
comes with an additional script xiv.sh which will open a file
selection box if called without any file. File selection box requires
kdialog (KDE), zenity (GNOME) or Xdialog. This script is meant to use
xiv from a desktop environment.

Additionnal information can be found on http://lordikc.free.fr/wordpress/?p=701.

.B Examples:

  xiv -browse /images/image1.jpg

Opens images1.jpg as well as every file in the /images directory.

  xiv -shuffle /images/*

Opens every files in /images in random order.

.SH OPTIONS
.IP "-geometry widthxheight+ox+oy"
Size of the window, default is the screen size.
.IP   "-threads #"
Number of drawing threads, default is to auto-detect # of cores.
.IP   "-cache #" 
Number of cached images (default 5).
.IP   -no-autorot 
Disable auto rotate according to EXIF tags.
.IP   -no-overview 
Don't display overview.
.IP   -fullscreen
Start in fullscreen mode
.IP   -histogram 
Display histogram.
.IP   -grid 
Display grid.
.IP   -browse 
Expand the list of files by browsing the directory of the first file
given on the command line.
.IP   -shuffle 
Shuffle the file list.
.IP   -bilinear
Turn on bilinear interpolation.
.IP   "-fifo filename"
Fifo file for listening incoming commands, default is no command file.
.IP   -v 
Verbose mode.
.SH CONTROLS

.B Key based:
 - q/Q Quit
 - n/p Next/previous image in the list
 - Shift+n/p Next/previous x10 image in the list
 - ' '/. Center view on pointer
 - z/+ Zoom
 - u/- Unzoom
 - c/C Contrast
 - g/G Gamma
 - l/L Luminosity
 - v   Reset Luminosity/Contrast
 - i   Invert colors
 - Fn  Memorize current pixel coordinate as nth point
 - s   Show/hide points
 - f   Toggle Full Screen
 - h   Toggle display histogram
 - b   Toggle bilinear interpolation
 - o   Toggle display overview
 - m   Toggle displlay grid
 - r/=/0 Reset view
 - 1-9 Set zoom level to 1/1..9
 - [Alt+]1-9 Set zoom level to 1..9
 - Left/Right/Up/Down pan
 - Shift+Left/Right/Up/Down fine pan
 - / or * rotate around center of window by 90 degrees increments rounding angle to n x 90 degrees
 - Alt+Left/Right rotate around center of window
 - Shift+Alt+Left/Right fine rotate around center of window

.B Mouse based:
 - Left button+Drag Pan
 - Shift+Left button+Drag Upper-Left -> Lower Right : Zoom on zone, Lower-Right -> Upper Left Unzoom from zone.
 - Wheel Zoom/Unzoom keeping pointer position
 - Shift+Wheel Fine Zoom/Unzoom keeping pointer position
 - Alt+Wheel Rotate around pointer
 - Shift+Alt+Wheel Fine rotate around pointer
 - Button middle Previous image
 - Button right Next image
.SH FIFO COMMANDS
 - l filename: load a new image
 - z zoom_level: if zoom_level <0 fit image in window
 - c x y: Center view on (x,y) (image pixel coordinates system)
 - m x y: Move view of (x,y) (image pixel coordinates system)
 - q: quit

.B Example

xiv -fifo /tmp/fifo &

echo "l image.ppm" > /tmp/fifo

.SH FILES
.I /usr/share/xiv/xiv.ppm
.RS
Default XIV image.
.SH ENVIRONMENT
.SH DIAGNOSTICS
.SH BUGS
Mouse interaction conflict with default LXDE mouse shortcuts. You need
to change LXDE's mouse shortcuts (Alt+Wheel).
.SH AUTHOR
Gilles BERNARD <lordikc at free dot fr>
.SH "SEE ALSO"
